---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myrs

spec:
  replicas: 2
  selector:
    matchLabels:
      app: swiggy
  template:
    metadata:
      labels:
        app: swiggy


    spec:
      containers:
        - name: cont2
          image: shaikmustafa/dm
          ports:
            - containerPort: 80
##########################################################

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: myrc2

spec:
  replicas: 2
  selector:
    app: swiggy
  template:
    metadata:
      labels:
        app: swiggy


    spec:
      containers:
        - name: cont2
          image: shaikmustafa/dm
          ports:
            - containerPort: 80
